services:
  db:
    image: postgres:13
    container_name: pg-appname
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: appname
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  odoo:
    image: odoo:16.0
    container_name: appname
    depends_on:
      - db
    ports:
      - '8213:8069'
    command: [
      '--log-level=debug',
    ]
    volumes:
      - ./conf:/etc/odoo
      - ./addons:/mnt/extra-addons


